// USER TYPES
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
// UI TYPES
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const REMOVE_LOADING = 'REMOVE_LOADING';

// MOVIE DATA TYPES
export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const TOP_MOVIES = 'TOP_MOVIES';
export const POPULAR_MOVIES = 'POPULAR_MOVIES';
export const UPCOMMING_MOVIES = 'UPCOMMING_MOVIES';
